// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema.proto

package schema

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Reading struct {
	Datetime             uint32   `protobuf:"fixed32,1,opt,name=datetime,proto3" json:"datetime,omitempty"`
	ElectricityHigh      float32  `protobuf:"fixed32,2,opt,name=ElectricityHigh,proto3" json:"ElectricityHigh,omitempty"`
	ElectricityLow       float32  `protobuf:"fixed32,3,opt,name=ElectricityLow,proto3" json:"ElectricityLow,omitempty"`
	Gas                  float32  `protobuf:"fixed32,4,opt,name=Gas,proto3" json:"Gas,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reading) Reset()         { *m = Reading{} }
func (m *Reading) String() string { return proto.CompactTextString(m) }
func (*Reading) ProtoMessage()    {}
func (*Reading) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_269a0a52f74ad4f0, []int{0}
}
func (m *Reading) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reading.Unmarshal(m, b)
}
func (m *Reading) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reading.Marshal(b, m, deterministic)
}
func (dst *Reading) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reading.Merge(dst, src)
}
func (m *Reading) XXX_Size() int {
	return xxx_messageInfo_Reading.Size(m)
}
func (m *Reading) XXX_DiscardUnknown() {
	xxx_messageInfo_Reading.DiscardUnknown(m)
}

var xxx_messageInfo_Reading proto.InternalMessageInfo

func (m *Reading) GetDatetime() uint32 {
	if m != nil {
		return m.Datetime
	}
	return 0
}

func (m *Reading) GetElectricityHigh() float32 {
	if m != nil {
		return m.ElectricityHigh
	}
	return 0
}

func (m *Reading) GetElectricityLow() float32 {
	if m != nil {
		return m.ElectricityLow
	}
	return 0
}

func (m *Reading) GetGas() float32 {
	if m != nil {
		return m.Gas
	}
	return 0
}

func init() {
	proto.RegisterType((*Reading)(nil), "Reading")
}

func init() { proto.RegisterFile("schema.proto", fileDescriptor_schema_269a0a52f74ad4f0) }

var fileDescriptor_schema_269a0a52f74ad4f0 = []byte{
	// 132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0xce, 0x48,
	0xcd, 0x4d, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xea, 0x64, 0xe4, 0x62, 0x0f, 0x4a, 0x4d,
	0x4c, 0xc9, 0xcc, 0x4b, 0x17, 0x92, 0xe2, 0xe2, 0x48, 0x49, 0x2c, 0x49, 0x2d, 0xc9, 0xcc, 0x4d,
	0x95, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0f, 0x82, 0xf3, 0x85, 0x34, 0xb8, 0xf8, 0x5d, 0x73, 0x52,
	0x93, 0x4b, 0x8a, 0x32, 0x93, 0x33, 0x4b, 0x2a, 0x3d, 0x32, 0xd3, 0x33, 0x24, 0x98, 0x14, 0x18,
	0x35, 0x98, 0x82, 0xd0, 0x85, 0x85, 0xd4, 0xb8, 0xf8, 0x90, 0x84, 0x7c, 0xf2, 0xcb, 0x25, 0x98,
	0xc1, 0x0a, 0xd1, 0x44, 0x85, 0x04, 0xb8, 0x98, 0xdd, 0x13, 0x8b, 0x25, 0x58, 0xc0, 0x92, 0x20,
	0x66, 0x12, 0x1b, 0xd8, 0x49, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x88, 0xbf, 0x45, 0x90,
	0xa2, 0x00, 0x00, 0x00,
}
